# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
